### PR TITLE
refactor: cleanup

### PR DESCRIPTION
**Pull request by dennyscode**
Ticket: https://lifi.atlassian.net/browse/LF-10010

From:
Screenshot 2024-09-11 at 23 11 54

To:
Screenshot 2024-09-11 at 23 14 03

Still to be done:

- [ ] Check dependency arrays...
- [ ] ...add exceptions if needed to calm down the linter

### CODE REVIEW

**Review by oktapodia — COMMENTED** [review]
LGTM but the todo comments which does not give any solution or anything to look at e.g. `// todo: check dep array` What does that mean? Do we need to change something to fix it?

**Review by oktapodia — APPROVED** [review]
LGTM

**Comment by dennyscode** [comment]
We also migrated eslint to v9 in this branch!

We are left with the following lint warnings:

```
  9:13  warning  'partnerTheme' is defined but never used  @typescript-eslint/no-unused-vars
  11:13  warning  'lng' is defined but never used  @typescript-eslint/no-unused-vars
  8:13  warning  'partnerTheme' is defined but never used  @typescript-eslint/no-unused-vars
  9:13  warning  'partnerTheme' is defined but never used  @typescript-eslint/no-unused-vars
  26:22  warning  'reset' is defined but never used  @typescript-eslint/no-unused-vars
  6:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  4:40  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   53:18  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   58:18  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   64:8   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   65:18  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  272:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  67:6  warning  'theme' is defined but never used  @typescript-eslint/no-unused-vars
  69:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  23:64  warning  'theme' is defined but never used  @typescript-eslint/no-unused-vars
  2:22  warning  'darken' is defined but never used  @typescript-eslint/no-unused-vars
  53:9  warning  'handleClick' is assigned a value but never used  @typescript-eslint/no-unused-vars
  16:49  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  19:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  145:48  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  146:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   40:58  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  137:58  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  183:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  187:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  191:16  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  13:24  warning  'lang' is defined but never used  @typescript-eslint/no-unused-vars
  88:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  7:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  11:14  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  102:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  104:11  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  163:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  209:11  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```

image

**Comment by dennyscode** [comment]
I also tested with husky with a forbidden `console.log` and the commit failed as expected:

image

**Comment by dennyscode** [comment]
It will still return the following warning when running `yarn eslint`:

image

**Pull request closed without merging**
